dmitry mikhaylov: added collection homework file
eugene-okulik/invizrogue pull request #3
Opened 2024-12-12 21:03 UTC by invizrogue

Добавлено решения ДЗ №4

2024-12-13 07:31 UTC, eugene-okulik requested changes
Не нашел выполнение вот этого:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

Ну и циклы здесь не очень нужны пока. Они ничего не упрощают. Можно было просто по ключам обращаться

2024-12-13 09:33 UTC, invizrogue commented
Скорректировал решение: добавил в элемент 'dict' ключ 'i am a tuple' со значением 42

2024-12-14 10:37 UTC, eugene-okulik requested changes
Проверочку на внимательность не прошел )))

2024-12-14 10:37 UTC, eugene-okulik commented on homework/dmitry_mikhaylov/homework_4/collection_actions.py
> +my_dict['dict']['i am a tuple'] = 42
В задании было:

> добавьте элемент с ключом ('i am a tuple',) и любым значением

У тебя выполнено как если бы там было

> добавьте элемент с ключом 'i am a tuple' и любым значением

`('i am a tuple',) ` - кортеж с одним элементом. И именно это и должно быть ключом. Сейчас ключ - строка `'i am a tuple'`

2024-12-16 05:26 UTC, invizrogue commented
Да, есть такое. Надо собраться

2024-12-16 12:05 UTC, eugene-okulik approved these changes
:+1:

2024-12-16 12:05 UTC, merged